In [1]:
import pandas as pd

In [3]:
people = {
    "first": ["Rohit", "Virat", "Jasprit", "Shubman", "Hardik", "Rishabh", "Suryakumar", "Ravindra", "Kuldeep", "Arshdeep", "Axar"],
    "last": ["Sharma", "Kohli", "Bumrah", "Gill", "Pandya", "Pant", "Yadav", "Jadeja", "Yadav", "Singh", "Patel"],
    "email": [
        "rohit.sharma@email.com", 
        "virat.kohli@email.com", 
        "jasprit.bumrah@email.com", 
        "shubman.gill@email.com", 
        "hardik.pandya@email.com", 
        "rishabh.pant@email.com", 
        "suryakumar.yadav@email.com", 
        "ravindra.jadeja@email.com", 
        "kuldeep.yadav@email.com", 
        "arshdeep.singh@email.com", 
        "axar.patel@email.com"
    ]
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [7]:
df.columns = ['first name', 'last name', 'email']

In [8]:
df

    first name last name                       email
0        Rohit    Sharma      rohit.sharma@email.com
1        Virat     Kohli       virat.kohli@email.com
2      Jasprit    Bumrah    jasprit.bumrah@email.com
3      Shubman      Gill      shubman.gill@email.com
4       Hardik    Pandya     hardik.pandya@email.com
5      Rishabh      Pant      rishabh.pant@email.com
6   Suryakumar     Yadav  suryakumar.yadav@email.com
7     Ravindra    Jadeja   ravindra.jadeja@email.com
8      Kuldeep     Yadav     kuldeep.yadav@email.com
9     Arshdeep     Singh    arshdeep.singh@email.com
10        Axar     Patel        axar.patel@email.com

In [9]:
df.columns = [x.upper() for x in df.columns]

In [10]:
df

    FIRST NAME LAST NAME                       EMAIL
0        Rohit    Sharma      rohit.sharma@email.com
1        Virat     Kohli       virat.kohli@email.com
2      Jasprit    Bumrah    jasprit.bumrah@email.com
3      Shubman      Gill      shubman.gill@email.com
4       Hardik    Pandya     hardik.pandya@email.com
5      Rishabh      Pant      rishabh.pant@email.com
6   Suryakumar     Yadav  suryakumar.yadav@email.com
7     Ravindra    Jadeja   ravindra.jadeja@email.com
8      Kuldeep     Yadav     kuldeep.yadav@email.com
9     Arshdeep     Singh    arshdeep.singh@email.com
10        Axar     Patel        axar.patel@email.com

In [11]:
df.columns = df.columns.str.replace(' ', '_')

In [12]:
df

    FIRST_NAME LAST_NAME                       EMAIL
0        Rohit    Sharma      rohit.sharma@email.com
1        Virat     Kohli       virat.kohli@email.com
2      Jasprit    Bumrah    jasprit.bumrah@email.com
3      Shubman      Gill      shubman.gill@email.com
4       Hardik    Pandya     hardik.pandya@email.com
5      Rishabh      Pant      rishabh.pant@email.com
6   Suryakumar     Yadav  suryakumar.yadav@email.com
7     Ravindra    Jadeja   ravindra.jadeja@email.com
8      Kuldeep     Yadav     kuldeep.yadav@email.com
9     Arshdeep     Singh    arshdeep.singh@email.com
10        Axar     Patel        axar.patel@email.com

In [13]:
df.columns = [x.lower() for x in df.columns]

In [14]:
df

    first_name last_name                       email
0        Rohit    Sharma      rohit.sharma@email.com
1        Virat     Kohli       virat.kohli@email.com
2      Jasprit    Bumrah    jasprit.bumrah@email.com
3      Shubman      Gill      shubman.gill@email.com
4       Hardik    Pandya     hardik.pandya@email.com
5      Rishabh      Pant      rishabh.pant@email.com
6   Suryakumar     Yadav  suryakumar.yadav@email.com
7     Ravindra    Jadeja   ravindra.jadeja@email.com
8      Kuldeep     Yadav     kuldeep.yadav@email.com
9     Arshdeep     Singh    arshdeep.singh@email.com
10        Axar     Patel        axar.patel@email.com

In [15]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'})

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [16]:
df

    first_name last_name                       email
0        Rohit    Sharma      rohit.sharma@email.com
1        Virat     Kohli       virat.kohli@email.com
2      Jasprit    Bumrah    jasprit.bumrah@email.com
3      Shubman      Gill      shubman.gill@email.com
4       Hardik    Pandya     hardik.pandya@email.com
5      Rishabh      Pant      rishabh.pant@email.com
6   Suryakumar     Yadav  suryakumar.yadav@email.com
7     Ravindra    Jadeja   ravindra.jadeja@email.com
8      Kuldeep     Yadav     kuldeep.yadav@email.com
9     Arshdeep     Singh    arshdeep.singh@email.com
10        Axar     Patel        axar.patel@email.com

In [17]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)

In [18]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [19]:
df.loc[2]

first                     Jasprit
last                       Bumrah
email    jasprit.bumrah@email.com
Name: 2, dtype: str

In [22]:
df.loc[2] = ['Jasprit', 'Khan', 'jasprit.khan@email.com']

In [23]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit    Khan      jasprit.khan@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [24]:
df.loc[2, ['last', 'email']]

last                       Khan
email    jasprit.khan@email.com
Name: 2, dtype: str

In [25]:
df.loc[2, ['last', 'email']] = ['Bumrah', 'jasprit.bumrah@email.com']

In [26]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [27]:
df.loc[2, 'last'] = 'Khan'

In [28]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit    Khan    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [29]:
df.at[2, 'last'] = 'Bumrah'

In [30]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [31]:
filt = (df['email'] == 'jasprit.bumrah@email.com')
df[filt]

     first    last                     email
2  Jasprit  Bumrah  jasprit.bumrah@email.com