# Part 6: Adding and Removing Rows/Columns

In this section, we'll learn how to modify the structure of our DataFrame by creating new columns, dropping existing ones, and adding/removing rows.

In [ ]:
people = {
    "first": ["Rohit", "Virat", "Jasprit", "Shubman", "Hardik", "Rishabh", "Suryakumar", "Ravindra", "Kuldeep", "Arshdeep", "Axar"],
    "last": ["Sharma", "Kohli", "Bumrah", "Gill", "Pandya", "Pant", "Yadav", "Jadeja", "Yadav", "Singh", "Patel"],
    "email": [
        "rohit.sharma@email.com", 
        "virat.kohli@email.com", 
        "jasprit.bumrah@email.com", 
        "shubman.gill@email.com", 
        "hardik.pandya@email.com", 
        "rishabh.pant@email.com", 
        "suryakumar.yadav@email.com", 
        "ravindra.jadeja@email.com", 
        "kuldeep.yadav@email.com", 
        "arshdeep.singh@email.com", 
        "axar.patel@email.com"
    ]
}

In [57]:
import pandas as pd

In [58]:
df = pd.DataFrame(people)

In [59]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [60]:
df['first'] + ' ' + df['last']

0         Rohit Sharma
1          Virat Kohli
2       Jasprit Bumrah
3         Shubman Gill
4        Hardik Pandya
5         Rishabh Pant
6     Suryakumar Yadav
7      Ravindra Jadeja
8        Kuldeep Yadav
9       Arshdeep Singh
10          Axar Patel
dtype: str

## Creating a New Column
We can create new columns by performing operations on existing ones. Here, we're combining 'first' and 'last' name into a single 'full_name' column.

In [61]:
df['full_name'] = df['first'] + ' ' + df['last']

In [62]:
df

         first    last                       email         full_name
0        Rohit  Sharma      rohit.sharma@email.com      Rohit Sharma
1        Virat   Kohli       virat.kohli@email.com       Virat Kohli
2      Jasprit  Bumrah    jasprit.bumrah@email.com    Jasprit Bumrah
3      Shubman    Gill      shubman.gill@email.com      Shubman Gill
4       Hardik  Pandya     hardik.pandya@email.com     Hardik Pandya
5      Rishabh    Pant      rishabh.pant@email.com      Rishabh Pant
6   Suryakumar   Yadav  suryakumar.yadav@email.com  Suryakumar Yadav
7     Ravindra  Jadeja   ravindra.jadeja@email.com   Ravindra Jadeja
8      Kuldeep   Yadav     kuldeep.yadav@email.com     Kuldeep Yadav
9     Arshdeep   Singh    arshdeep.singh@email.com    Arshdeep Singh
10        Axar   Patel        axar.patel@email.com        Axar Patel

In [63]:
df.drop(columns=['first', 'last'], inplace=True)

## Removing Columns
To remove columns, use the `drop()` method with the `columns` argument. Setting `inplace=True` makes the change permanent in the current DataFrame.

In [35]:
df

                         email         full_name
0       rohit.sharma@email.com      Rohit Sharma
1        virat.kohli@email.com       Virat Kohli
2     jasprit.bumrah@email.com    Jasprit Bumrah
3       shubman.gill@email.com      Shubman Gill
4      hardik.pandya@email.com     Hardik Pandya
5       rishabh.pant@email.com      Rishabh Pant
6   suryakumar.yadav@email.com  Suryakumar Yadav
7    ravindra.jadeja@email.com   Ravindra Jadeja
8      kuldeep.yadav@email.com     Kuldeep Yadav
9     arshdeep.singh@email.com    Arshdeep Singh
10        axar.patel@email.com        Axar Patel

In [64]:
df['full_name'].str.split(' ', expand=True)

             0       1
0        Rohit  Sharma
1        Virat   Kohli
2      Jasprit  Bumrah
3      Shubman    Gill
4       Hardik  Pandya
5      Rishabh    Pant
6   Suryakumar   Yadav
7     Ravindra  Jadeja
8      Kuldeep   Yadav
9     Arshdeep   Singh
10        Axar   Patel

## Splitting Columns
We can split a single column into multiple columns using `.str.split()`. Using `expand=True` returns a DataFrame instead of a list.

In [65]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)

In [66]:
df

                         email         full_name       first    last
0       rohit.sharma@email.com      Rohit Sharma       Rohit  Sharma
1        virat.kohli@email.com       Virat Kohli       Virat   Kohli
2     jasprit.bumrah@email.com    Jasprit Bumrah     Jasprit  Bumrah
3       shubman.gill@email.com      Shubman Gill     Shubman    Gill
4      hardik.pandya@email.com     Hardik Pandya      Hardik  Pandya
5       rishabh.pant@email.com      Rishabh Pant     Rishabh    Pant
6   suryakumar.yadav@email.com  Suryakumar Yadav  Suryakumar   Yadav
7    ravindra.jadeja@email.com   Ravindra Jadeja    Ravindra  Jadeja
8      kuldeep.yadav@email.com     Kuldeep Yadav     Kuldeep   Yadav
9     arshdeep.singh@email.com    Arshdeep Singh    Arshdeep   Singh
10        axar.patel@email.com        Axar Patel        Axar   Patel

In [67]:
new_row = pd.DataFrame([{'first': 'Abisheik'}])
df = pd.concat([df, new_row], ignore_index=True)

## Adding Rows
To add rows, we can use `pd.concat()` to join two DataFrames together. `ignore_index=True` ensures the resulting DataFrame has a clean, continuous index.

In [68]:
df

                         email         full_name       first    last
0       rohit.sharma@email.com      Rohit Sharma       Rohit  Sharma
1        virat.kohli@email.com       Virat Kohli       Virat   Kohli
2     jasprit.bumrah@email.com    Jasprit Bumrah     Jasprit  Bumrah
3       shubman.gill@email.com      Shubman Gill     Shubman    Gill
4      hardik.pandya@email.com     Hardik Pandya      Hardik  Pandya
5       rishabh.pant@email.com      Rishabh Pant     Rishabh    Pant
6   suryakumar.yadav@email.com  Suryakumar Yadav  Suryakumar   Yadav
7    ravindra.jadeja@email.com   Ravindra Jadeja    Ravindra  Jadeja
8      kuldeep.yadav@email.com     Kuldeep Yadav     Kuldeep   Yadav
9     arshdeep.singh@email.com    Arshdeep Singh    Arshdeep   Singh
10        axar.patel@email.com        Axar Patel        Axar   Patel
11                         NaN               NaN    Abisheik     NaN

In [69]:
df = pd.concat([df, new_row], ignore_index=True)

In [70]:
df

                         email         full_name       first    last
0       rohit.sharma@email.com      Rohit Sharma       Rohit  Sharma
1        virat.kohli@email.com       Virat Kohli       Virat   Kohli
2     jasprit.bumrah@email.com    Jasprit Bumrah     Jasprit  Bumrah
3       shubman.gill@email.com      Shubman Gill     Shubman    Gill
4      hardik.pandya@email.com     Hardik Pandya      Hardik  Pandya
5       rishabh.pant@email.com      Rishabh Pant     Rishabh    Pant
6   suryakumar.yadav@email.com  Suryakumar Yadav  Suryakumar   Yadav
7    ravindra.jadeja@email.com   Ravindra Jadeja    Ravindra  Jadeja
8      kuldeep.yadav@email.com     Kuldeep Yadav     Kuldeep   Yadav
9     arshdeep.singh@email.com    Arshdeep Singh    Arshdeep   Singh
10        axar.patel@email.com        Axar Patel        Axar   Patel
11                         NaN               NaN    Abisheik     NaN
12                         NaN               NaN    Abisheik     NaN

In [71]:
df.drop(index=12, inplace=True)

## Removing Rows
Rows can be removed by their index using the `drop()` method.

In [72]:
df

                         email         full_name       first    last
0       rohit.sharma@email.com      Rohit Sharma       Rohit  Sharma
1        virat.kohli@email.com       Virat Kohli       Virat   Kohli
2     jasprit.bumrah@email.com    Jasprit Bumrah     Jasprit  Bumrah
3       shubman.gill@email.com      Shubman Gill     Shubman    Gill
4      hardik.pandya@email.com     Hardik Pandya      Hardik  Pandya
5       rishabh.pant@email.com      Rishabh Pant     Rishabh    Pant
6   suryakumar.yadav@email.com  Suryakumar Yadav  Suryakumar   Yadav
7    ravindra.jadeja@email.com   Ravindra Jadeja    Ravindra  Jadeja
8      kuldeep.yadav@email.com     Kuldeep Yadav     Kuldeep   Yadav
9     arshdeep.singh@email.com    Arshdeep Singh    Arshdeep   Singh
10        axar.patel@email.com        Axar Patel        Axar   Patel
11                         NaN               NaN    Abisheik     NaN

In [73]:
remove_yadav = df['last'] == 'Yadav'
df.drop(index=df[remove_yadav].index, inplace=True)

You can also drop rows based on a condition by finding the indices that match the condition.

In [74]:
df

                        email        full_name     first    last
0      rohit.sharma@email.com     Rohit Sharma     Rohit  Sharma
1       virat.kohli@email.com      Virat Kohli     Virat   Kohli
2    jasprit.bumrah@email.com   Jasprit Bumrah   Jasprit  Bumrah
3      shubman.gill@email.com     Shubman Gill   Shubman    Gill
4     hardik.pandya@email.com    Hardik Pandya    Hardik  Pandya
5      rishabh.pant@email.com     Rishabh Pant   Rishabh    Pant
7   ravindra.jadeja@email.com  Ravindra Jadeja  Ravindra  Jadeja
9    arshdeep.singh@email.com   Arshdeep Singh  Arshdeep   Singh
10       axar.patel@email.com       Axar Patel      Axar   Patel
11                        NaN              NaN  Abisheik     NaN